# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-20 18:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import policy_tracker_app.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
                ('inPower', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=500)),
                ('background_image', models.ImageField(blank=True, upload_to=policy_tracker_app.models.UploadToPathAndRename('Y:\\Users\\benji\\Documents\\University\\Year 2\\WAD2\\policy-tracker\\media\\country_images'))),
                ('map_image', models.ImageField(blank=True, upload_to=policy_tracker_app.models.UploadToPathAndRename('Y:\\Users\\benji\\Documents\\University\\Year 2\\WAD2\\policy-tracker\\media\\map_images'))),
                ('slug', models.SlugField()),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=1024)),
                ('status', models.CharField(max_length=64)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policy_tracker_app.Category')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policy_tracker_app.Country')),
            ],
            options={
                'verbose_name_plural': 'Policies',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website', models.URLField(blank=True)),
                ('picture', models.ImageField(blank=True, upload_to=policy_tracker_app.models.UploadToPathAndRename('Y:\\Users\\benji\\Documents\\University\\Year 2\\WAD2\\policy-tracker\\media\\profile_images'))),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
